# These are supported funding model platforms

github: [aymanviola1-creator]

# Custom funding links
custom:
  - "https://aymanviola1-creator.github.io/free-web-tools/pro-bundle.html"
  - "https://aymanviola1-creator.github.io/free-web-tools/#support"
  # Bitcoin: 1HBUAq6JfSbgbjsyZokAHWXnGdS7z4myNy
  # Ethereum: 0x6E8b70656f71BAe32019FC37927Fd43f4C8C40c6
  # Solana: BPKe4HjmHANv1X412JyYka4Lk2zt35kjH64zZNhcXMWL
